version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running application
      - npm install

      # Build Project
      - npm run build

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
artifacts:
  files:
    - '**/*'